create sequence seq_cart
start with 1;
create sequence seq_user
start with 1;
create sequence seq_shops
start with 1;
create sequence seq_report
start with 1;
create sequence seq_product
start with 1;
create sequence seq_order
start with 1;
create sequence seq_payment
start with 1;
create sequence seq_collectionslot
start with 1;
create sequence seq_review
start with 1;
create sequence seq_wishlist
start with 1;
create sequence seq_discount
start with 1;